#!/usr/bin/env bash
# DuckDNS dynamic DNS sync — Raspberry Pi setup script
#
# What this script does:
#   1. Creates ~/duckdns/duck.sh (the actual IP-update script)
#   2. Runs it once to verify your token is correct
#   3. Installs a cron job to re-run every 5 minutes (idempotent)
#
# Why: Home ISPs reassign public IPs on router reboot. DuckDNS maps a fixed
# subdomain to your current IP, so SSH/VPN connections always have a stable
# hostname regardless of IP changes.
#
# Prerequisites:
#   1. Register at https://www.duckdns.org (free, login with Google/GitHub)
#   2. Create a subdomain (e.g. myhome → myhome.duckdns.org)
#   3. Copy your token (UUID shown at the top of the DuckDNS dashboard)
#   4. Fill in DUCKDNS_DOMAIN and DUCKDNS_TOKEN below, then run:
#        bash duckdns_sync.sh

set -euo pipefail

# ── Configuration — edit these two lines before running ───────────────────────
DUCKDNS_DOMAIN="YOUR_DUCKDNS_DOMAIN"   # subdomain only, e.g. myhome
DUCKDNS_TOKEN="YOUR_DUCKDNS_TOKEN"     # UUID from your DuckDNS dashboard
# ──────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="${HOME}/duckdns"
SCRIPT_PATH="${SCRIPT_DIR}/duck.sh"
LOG_PATH="${SCRIPT_DIR}/duck.log"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ── Guard: catch unfilled placeholders ────────────────────────────────────────

if [[ "$DUCKDNS_DOMAIN" == "YOUR_DUCKDNS_DOMAIN" || \
      "$DUCKDNS_TOKEN"  == "YOUR_DUCKDNS_TOKEN" ]]; then
    error "Fill in DUCKDNS_DOMAIN and DUCKDNS_TOKEN at the top of this script first."
fi

info "Setting up DuckDNS for: ${DUCKDNS_DOMAIN}.duckdns.org"

# ── Step 1: Create the update script ──────────────────────────────────────────

mkdir -p "$SCRIPT_DIR"

cat > "$SCRIPT_PATH" << EOF
#!/usr/bin/env bash
# Auto-generated by duckdns_sync.sh
curl -s "https://www.duckdns.org/update?domains=${DUCKDNS_DOMAIN}&token=${DUCKDNS_TOKEN}&ip=" \\
    --output "${LOG_PATH}" \\
    --max-time 10
EOF

chmod +x "$SCRIPT_PATH"
info "Created: $SCRIPT_PATH"

# ── Step 2: Test once ──────────────────────────────────────────────────────────

info "Testing DuckDNS update (checking token validity)..."
"$SCRIPT_PATH"

RESULT=$(cat "$LOG_PATH" 2>/dev/null || echo "")
if [[ "$RESULT" == "OK" ]]; then
    info "✅ DuckDNS responded OK — token and domain are valid."
else
    warn "Unexpected response from DuckDNS: '${RESULT}'"
    warn "Double-check your DUCKDNS_DOMAIN and DUCKDNS_TOKEN, then re-run."
    exit 1
fi

# ── Step 3: Install cron job (idempotent) ─────────────────────────────────────
# Marker comment prevents duplicate entries on repeated runs.

CRON_MARKER="# duckdns-auto-update"
CRON_JOB="*/5 * * * * ${SCRIPT_PATH} >> ${LOG_PATH} 2>&1 ${CRON_MARKER}"

if crontab -l 2>/dev/null | grep -qF "$CRON_MARKER"; then
    info "Cron job already installed — skipping."
else
    (crontab -l 2>/dev/null; echo "$CRON_JOB") | crontab -
    info "Cron job installed: IP update runs every 5 minutes."
fi

# ── Done ───────────────────────────────────────────────────────────────────────

echo ""
info "✅ DuckDNS setup complete."
echo ""
echo "  Verify DNS resolves to your public IP:"
echo "    nslookup ${DUCKDNS_DOMAIN}.duckdns.org"
echo "    curl https://api.ipify.org/"
echo "  Both should return the same IP address."
echo ""
echo "  Connect from anywhere:"
echo "    ssh -p 22222 YOUR_USERNAME@${DUCKDNS_DOMAIN}.duckdns.org"
echo "    ssh -p 22222 -L 2053:localhost:2053 YOUR_USERNAME@${DUCKDNS_DOMAIN}.duckdns.org"
echo "    (second form opens X-UI panel via SSH tunnel at http://localhost:2053/YOUR_PANEL_PATH/)"
